RMS_COLUMN_NAMES = ["ACCNTNUM", "LOCNUM", "LOCNAME", "STREETNAME", "CITY", "STATECODE", "POSTALCODE", "LATITUDE",
                    "LONGITUDE", "NUMBLDGS", "BLDGSCHEME", "BLDGCLASS", "OCCSCHEME", "OCCTYPE", "YEARBUILT",
                    "FLOORAREA", "AREAUNIT", "USECONTENTVALUE", "BLDGVALUATION", "NUMSTORIES", "INCEPTDATE",
                    "EXPIREDATE", "CNTRYSCHEME", "CNTRYCODE", "EQCV1LIMIT", "EQCV1LCUR", "EQCV1DED", "EQCV1DCUR",
                    "EQCV1VAL", "EQCV1VCUR", "EQCV2LIMIT", "EQCV2LCUR", "EQCV2DED", "EQCV2DCUR", "EQCV2VAL",
                    "EQCV2VCUR", "EQCV2CVM", "EQCV2EQSLG", "EQCV2PCTSP", "EQCV3LIMIT", "EQCV3LCUR", "EQCV3DED",
                    "EQCV3DCUR", "EQCV3VAL", "EQCV3VCUR", "EQCV3WAIT", "EQCV3POI", "WSCV1LIMIT", "WSCV1LCUR",
                    "WSCV1DED", "WSCV1DCUR", "WSCV1VAL", "WSCV1VCUR", "WSCV2LIMIT", "WSCV2LCUR", "WSCV2DED",
                    "WSCV2DCUR", "WSCV2VAL", "WSCV2VCUR", "WSCV2CVM", "WSCV3LIMIT", "WSCV3LCUR", "WSCV3DED",
                    "WSCV3DCUR", "WSCV3VAL", "WSCV3VCUR", "WSCV3WAIT", "WSCV3POI", "WSCV4LIMIT", "WSCV4LCUR",
                    "WSCV4DED", "WSCV4DCUR", "WSCV4VAL", "WSCV4VCUR", "WSCV5LIMIT", "WSCV5LCUR", "WSCV5DED",
                    "WSCV5DCUR", "WSCV5VAL", "WSCV5VCUR", "WSCV6LIMIT", "WSCV6LCUR", "WSCV6DED", "WSCV6DCUR",
                    "WSCV6VAL", "WSCV6VCUR", "WSCV6CVM", "WSCV7LIMIT", "WSCV7LCUR", "WSCV7DED", "WSCV7DCUR", "WSCV7VAL",
                    "WSCV7VCUR", "WSCV7WAIT", "WSCV7POI", "WSCV8LIMIT", "WSCV8LCUR", "WSCV8DED", "WSCV8DCUR",
                    "WSCV8VAL", "WSCV8VCUR", "WSCV9LIMIT", "WSCV9LCUR", "WSCV9DED", "WSCV9DCUR", "WSCV9VAL",
                    "WSCV9VCUR", "WSCV9CVM", "WSCV10LMT", "WSCV10LCUR", "WSCV10DED", "WSCV10DCUR", "WSCV10VAL",
                    "WSCV10VCUR", "WSCV10WAIT", "WSCV10POI", "TOCV1LIMIT", "TOCV1LCUR", "TOCV1DED", "TOCV1DCUR",
                    "TOCV1VAL", "TOCV1VCUR", "TOCV2LIMIT", "TOCV2LCUR", "TOCV2DED", "TOCV2DCUR", "TOCV2VAL",
                    "TOCV2VCUR", "TOCV2CVM", "TOCV3LIMIT", "TOCV3LCUR", "TOCV3DED", "TOCV3DCUR", "TOCV3VAL",
                    "TOCV3VCUR", "TOCV3WAIT", "TOCV3POI", "TOCV4LIMIT", "TOCV4LCUR", "TOCV4DED", "TOCV4DCUR",
                    "TOCV4VAL", "TOCV4VCUR", "TOCV5LIMIT", "TOCV5LCUR", "TOCV5DED", "TOCV5DCUR", "TOCV5VAL",
                    "TOCV5VCUR", "TOCV6LIMIT", "TOCV6LCUR", "TOCV6DED", "TOCV6DCUR", "TOCV6VAL", "TOCV6VCUR",
                    "TOCV6CVM", "TOCV7LIMIT", "TOCV7LCUR", "TOCV7DED", "TOCV7DCUR", "TOCV7VAL", "TOCV7VCUR",
                    "TOCV7WAIT", "TOCV7POI", "TOCV8LIMIT", "TOCV8LCUR", "TOCV8DED", "TOCV8DCUR", "TOCV8VAL",
                    "TOCV8VCUR", "TOCV9LIMIT", "TOCV9LCUR", "TOCV9DED", "TOCV9DCUR", "TOCV9VAL", "TOCV9VCUR",
                    "TOCV9CVM", "TOCV10LMT", "TOCV10LCUR", "TOCV10DED", "TOCV10DCUR", "TOCV10VAL", "TOCV10VCUR",
                    "TOCV10WAIT", "TOCV10POI", "FLCV1LIMIT", "FLCV1LCUR", "FLCV1DED", "FLCV1DCUR", "FLCV1VAL",
                    "FLCV1VCUR", "FLCV2LIMIT", "FLCV2LCUR", "FLCV2DED", "FLCV2DCUR", "FLCV2VAL", "FLCV2VCUR",
                    "FLCV2CVM", "FLCV3LIMIT", "FLCV3LCUR", "FLCV3DED", "FLCV3DCUR", "FLCV3VAL", "FLCV3VCUR",
                    "FLCV3WAIT", "FLCV3POI", "FLCV4LIMIT", "FLCV4LCUR", "FLCV4DED", "FLCV4DCUR", "FLCV4VAL",
                    "FLCV4VCUR", "FLCV5LIMIT", "FLCV5LCUR", "FLCV5DED", "FLCV5DCUR", "FLCV5VAL", "FLCV5VCUR",
                    "FLCV6LIMIT", "FLCV6LCUR", "FLCV6DED", "FLCV6DCUR", "FLCV6VAL", "FLCV6VCUR", "FLCV6CVM",
                    "FLCV7LIMIT", "FLCV7LCUR", "FLCV7DED", "FLCV7DCUR", "FLCV7VAL", "FLCV7VCUR", "FLCV7WAIT",
                    "FLCV7POI", "FLCV8LIMIT", "FLCV8LCUR", "FLCV8DED", "FLCV8DCUR", "FLCV8VAL", "FLCV8VCUR",
                    "FLCV9LIMIT", "FLCV9LCUR", "FLCV9DED", "FLCV9DCUR", "FLCV9VAL", "FLCV9VCUR", "FLCV9CVM",
                    "FLCV10LMT", "FLCV10LCUR", "FLCV10DED", "FLCV10DCUR", "FLCV10VAL", "FLCV10VCUR", "FLCV10WAIT",
                    "FLCV10POI", "FRCV1LIMIT", "FRCV1LCUR", "FRCV1DED", "FRCV1DCUR", "FRCV1VAL", "FRCV1VCUR",
                    "FRCV2LIMIT", "FRCV2LCUR", "FRCV2DED", "FRCV2DCUR", "FRCV2VAL", "FRCV2VCUR", "FRCV2CVM",
                    "FRCV3LIMIT", "FRCV3LCUR", "FRCV3DED", "FRCV3DCUR", "FRCV3VAL", "FRCV3VCUR", "FRCV3WAIT",
                    "FRCV3POI", "FRCV4LIMIT", "FRCV4LCUR", "FRCV4DED", "FRCV4DCUR", "FRCV4VAL", "FRCV4VCUR",
                    "FRCV5LIMIT", "FRCV5LCUR", "FRCV5DED", "FRCV5DCUR", "FRCV5VAL", "FRCV5VCUR", "FRCV6LIMIT",
                    "FRCV6LCUR", "FRCV6DED", "FRCV6DCUR", "FRCV6VAL", "FRCV6VCUR", "FRCV6CVM", "FRCV7LIMIT",
                    "FRCV7LCUR", "FRCV7DED", "FRCV7DCUR", "FRCV7VAL", "FRCV7VCUR", "FRCV7WAIT", "FRCV7POI",
                    "FRCV8LIMIT", "FRCV8LCUR", "FRCV8DED", "FRCV8DCUR", "FRCV8VAL", "FRCV8VCUR", "FRCV9LIMIT",
                    "FRCV9LCUR", "FRCV9DED", "FRCV9DCUR", "FRCV9VAL", "FRCV9VCUR", "FRCV9CVM", "FRCV10LMT",
                    "FRCV10LCUR", "FRCV10DED", "FRCV10DCUR", "FRCV10VAL", "FRCV10VCUR", "FRCV10WAIT", "FRCV10POI",
                    "TRCV1LIMIT", "TRCV1LCUR", "TRCV1DED", "TRCV1DCUR", "TRCV1VAL", "TRCV1VCUR", "TRCV2LIMIT",
                    "TRCV2LCUR", "TRCV2DED", "TRCV2DCUR", "TRCV2VAL", "TRCV2VCUR", "TRCV2CVM", "TRCV3LIMIT",
                    "TRCV3LCUR", "TRCV3DED", "TRCV3DCUR", "TRCV3VAL", "TRCV3VCUR", "TRCV3WAIT", "TRCV3POI",
                    "TRCV4LIMIT", "TRCV4LCUR", "TRCV4DED", "TRCV4DCUR", "TRCV4VAL", "TRCV4VCUR", "TRCV5LIMIT",
                    "TRCV5LCUR", "TRCV5DED", "TRCV5DCUR", "TRCV5VAL", "TRCV5VCUR", "TRCV6LIMIT", "TRCV6LCUR",
                    "TRCV6DED", "TRCV6DCUR", "TRCV6VAL", "TRCV6VCUR", "TRCV6CVM", "TRCV7LIMIT", "TRCV7LCUR", "TRCV7DED",
                    "TRCV7DCUR", "TRCV7VAL", "TRCV7VCUR", "TRCV7WAIT", "TRCV7POI", "TRCV8LIMIT", "TRCV8LCUR",
                    "TRCV8DED", "TRCV8DCUR", "TRCV8VAL", "TRCV8VCUR", "TRCV9LIMIT", "TRCV9LCUR", "TRCV9DED",
                    "TRCV9DCUR", "TRCV9VAL", "TRCV9VCUR", "TRCV9CVM", "TRCV10LMT", "TRCV10LCUR", "TRCV10DED",
                    "TRCV10DCUR", "TRCV10VAL", "TRCV10VCUR", "TRCV10WAIT", "TRCV10POI", "EQSITELIM", "EQSITELCUR",
                    "EQSITEDED", "EQSITEDCUR", "EQCOMBINEDLIM", "EQCOMBINEDLCUR", "EQCOMBINEDDED", "EQCOMBINEDDCUR",
                    "EQBIZONE", "SHAPECONF", "STORYPROF", "OVERPROF", "REDUND", "TORSION", "CLADDING", "BLDGEXT",
                    "SHORTCOL", "MASINTPART", "ORNAMENT", "MECHELEC", "CONQUAL", "DURESS", "POUNDING", "TANK", "HAZEXP",
                    "ENGFOUND", "WALLSBRACD", "FRAMEBOLT", "TILTUPRET", "URMPROV", "STRUCTUP", "LANDSLIDE", "LIQUEFACT",
                    "SOILTYPE", "SOILMATCH", "LANDMATCH", "LIQUEMATCH", "FIRE1", "FIRE2", "FIRE3", "FIRE4", "FIRE5",
                    "FIRE6", "FIRE7", "FIRE8", "LANDCOV", "LIQUECOV", "SOILCOV", "SOILPERIOD", "SOILTHICKNESS",
                    "ALQPREZONE", "DUCTILITY", "LONGSPAN", "BASEISOL", "SIDINGTYPE", "PREFAB", "EQSLINS", "SCNDSUPPLY",
                    "EQSLSUSCEPTIBILITY", "SPNKLRTYPE", "YEARSPNKLR", "TSDEBRIS", "TSSCOUR", "TSSAFEDIST", "TSPROTECT",
                    "EQ_PACKAGE", "EQ_PROTECT", "EQ_SALVAGE", "EQ_SPECIESTORAGE", "SOILVS", "SOILVSMATCH", "BASINLOCID",
                    "DI", "CRITD", "N160CS", "T15", "WFF", "DISTRIV", "GWD", "DC", "LIQCV", "HDLIQMATCH", "PHI",
                    "ROUGH", "NDVI", "COHES", "LANDCV", "HDLANDMATCH", "EQSLOPE", "ELEV", "CTI", "PRECIP", "TOPO",
                    "HDSECMATCH", "URMCHIMNEY", "BUILTONSLOPE", "WSSITELIM", "WSSITELCUR", "WSSITEDED", "WSSITEDCUR",
                    "WSCOMBINEDLIM", "WSCOMBINEDLCUR", "WSCOMBINEDDED", "WSCOMBINEDDCUR", "DISTCOAST", "YEARUPGRAD",
                    "PCNTCOMPLT", "STARTDATE", "COMPDATE", "DESIGNCODE", "CONSTQUALI", "ROOFSYS", "ROOFGEOM",
                    "ROOFANCH", "ROOFAGE", "ROOFFRAME", "ROOFMAINT", "ROOFPARAPT", "ROOFEQUIP", "EXTORN", "CLADSYS",
                    "CLADRATE", "FOUNDSYS", "ARCHITECT", "MECHSIDE", "MECHGROUND", "RESISTDOOR", "RESISTOPEN",
                    "WINDMISSL", "VULNWIND", "VULNFLOOD", "FLOODPROT", "ELEVATION", "FLOODINDEX", "ELEVCOV",
                    "FLOODMISSL", "BASEMENT", "FLOOROCCUPANCY", 'BLDGHEIGHT', 'HEIGHTUNIT', 'DISTRICT', 'ADMIN5NAME',
                    'ADMIN4NAME', 'COUNTY', 'STATE', 'PRIMARYBLDG']

LOCATION_COLUMNS = ["ACCNTNUM", "LOCNUM", "LOCNAME", "PRIMARYBLDG", "SITENAME", "ADDRESSNUM",
                    "STREETNAME", "BLOCK", "BLOCKGROUP", "CITY", "COUNTY", "STATE", "STATECODE", "POSTALCODE",
                    "CNTRYCODE", "CNTRYSCHEME", "LONGITUDE", "LATITUDE"]

BUILDING_COLUMNS = ["NUMBLDGS", "NUMSTORIES", "FLOORAREA", "AREAUNIT", "BLDGHEIGHT", "HEIGHTUNIT", "NUMSTORIESBG",
                    "FINISHEDFLOOR", "FLOOROCCUPANCY", "BLDGCLASS", "BLDGSCHEME", "OCCTYPE", "OCCSCHEME", "YEARBUILT",
                    "YEARUPGRAD", "PCNTCOMPLT"]

EQ_VAL_COLUMNS = ["EQCV1VAL", "EQCV2VAL", "EQCV2CVM", "EQCV9VAL", "EQCV9CVM", "EQCV3VAL"]
EQ_SITE_COLUMNS = ["EQSITEDED", "EQCOMBINEDDED", "EQCV1DED", "EQCV2DED", "EQCV9DED", "EQCV3DED", "EQSITELIM",
                   "EQCOMBINEDLIM", "EQCV1LIMIT", "EQCV2LIMIT", "EQCV9LIMIT", "EQCV3LIMIT"]
WS_VAL_COLUMNS = ["WSCV1VAL", "WSCV2VAL", "WSCV2CVM", "WSCV9VAL", "WSCV9CVM", "WSCV3VAL"]
WS_SITE_COLUMNS = ["WSSITEDED", "WSCOMBINEDDED", "WSCV1DED", "WSCV2DED", "WSCV9DED", "WSCV3DED", "WSSITELIM",
                   "WSCOMBINEDLIM", "WSCV1LIMIT", "WSCV2LIMIT", "WSCV9LIMIT", "WSCV3LIMIT"]
TO_VAL_COLUMNS = ["TOCV1VAL", "TOCV2VAL", "TOCV2CVM", "TOCV9VAL", "TOCV9CVM", "TOCV3VAL"]
TO_SITE_COLUMNS = ["TOSITEDED", "TOCOMBINEDDED", "TOCV1DED", "TOCV2DED", "TOCV9DED", "TOCV3DED", "TOSITELIM",
                   "TOCOMBINEDLIM", "TOCV1LIMIT", "TOCV2LIMIT", "TOCV9LIMIT", "TOCV3LIMIT"]
FR_VAL_COLUMNS = ["FRCV1VAL", "FRCV2VAL", "FRCV9VAL", "FRCV3VAL"]
FR_SITE_COLUMNS = ["FRSITEDED", "FRCOMBINEDDED", "FRCV1DED", "FRCV2DED", "FRCV9DED", "FRCV3DED", "FRSITELIM",
                   "FRCOMBINEDLIM", "FRCV1LIMIT", "FRCV2LIMIT", "FRCV9LIMIT", "FRCV3LIMIT"]
TR_VAL_COLUMNS = ["TRCV1VAL", "TRCV2VAL", "TRCV9VAL", "TRCV3VAL"]
TR_SITE_COLUMNS = ["TRSITEDED", "TRCOMBINEDDED", "TRCV1DED", "TRCV2DED", "TRCV9DED", "TRCV3DED", "TRSITELIM",
                   "TRCOMBINEDLIM", "TRCV1LIMIT", "TRCV2LIMIT", "TRCV9LIMIT", "TRCV3LIMIT"]
FL_VAL_COLUMNS = ["FLCV1VAL", "FLCV2VAL", "FLCV9VAL", "FLCV3VAL"]
FL_SITE_COLUMNS = ["FLSITEDED", "FLCOMBINEDDED", "FLCV1DED", "FLCV2DED", "FLCV9DED", "FLCV3DED", "FLSITELIM",
                   "FLCOMBINEDLIM", "FLCV1LIMIT", "FLCV2LIMIT", "FLCV9LIMIT", "FLCV3LIMIT"]

EQ_FEATURES = ["CONQUAL", "SHAPECONF", "STORYPROF", "OVERPROF", "CLADDING", "REDUND", "BLDGEXT", "SHORTCOL",
               "ORNAMENT", "MECHELEC", "DURESS", "POUNDING", "TANK", "ENGOUND", "HAZEXP", "BASEISOL", "FRAMEBOLT",
               "TILTUPRET", "URMPROV", "STRUCTUP", "TORSION", "MASINTPART", "EQSLINS", "EQSLSUSCEPTIBILITY",
               "SPNKLRTYPE", "WALLSBRACD", "EQCV2PCTSP", "EQCV6PCTSP", "EQCV6PCTSP"]

WS_FEATURES = ["BUILDINGELEVATION", "RMSBUILDINGELEVATION", "RMSBUILDINGELEVATION", "MATCH", "FLASHING",
               "IFMVERTICALEXPDIST", "IFMSTRUCTCONDITION", "IFMEQUIPBRACING", "IFMMISSILEEXP", "VULNWIND",
               "VULNFLOOD", "CONSTQUALI", "ROOFSYS", "ROOFGEOM", "ROOFANCH", "ROOFAGE", "ROOFFRAME",
               "ROOFMAINT", "ROOFPARAPT", "ROOFEQUIP", "BASEMENT", "EXTORN", "CLADSYS", "CLADRATE", "FOUNDSYS",
               "MECHGROUND", "MECHSIDE", "RESISTDOOR", "RESISTOPEN", "FLOODPROT", "WINDMISSL", "FLOODMISSL"
               "ARCHITECT", "DESIGNCODE"]

TO_FEATURES = ["ICEPROTECT", "PLUMBING", "ATTICINSUL", "ROOFVENT", "SNOWGUARDS", "TREEDENSITY"]

FL_FEATURES = ["FLIFMVERTICALEXPDIST", "FLOORTYPE", "FINISHEDFLOOR", "FLZONE"]

FR_FEATURES = ["WFHAZARD", "WFSUSCEPT", "WFTHREAT", "AREADESC", "SURFFUEL", "WFSPECCOND", "ACCESS", "NEARHIST"]
